name: Lab01 Variables and Secrets
run-name: Lab01 - ${{ github.actor }} is testing variables and secrets 🚀
permissions: read-all
on:
  workflow_dispatch:
env:
  MY_VARIABLE: "Hello, Github Actions!"
  DEMO_SECRET: ${{ secrets.DEMO_SECRET }}
jobs:
  variable-printing-job:
    runs-on: ubuntu-latest
    steps:
      - name: "Print MY_VARIABLE accessing it as a runner environment variable"
        run: echo "The value of MY_VARIABLE is ${MY_VARIABLE}!"
      - name: "Print MY_VARIABLE accessing it using contexts"
        run: echo "The value of MY_VARIABLE is ${{ env.MY_VARIABLE }}!"
      - name: "Print DEMO_SECRET accessing it as a runner environment variable"
        run: echo "The value of DEMO_SECRET is ${DEMO_SECRET}!"
      - name: "Print DEMO_SECRET accessing it using contexts"
        run: echo "The value of DEMO_SECRET is ${{ secrets.DEMO_SECRET }}!"
