name: Lab02 Reuse and Artifacts
run-name: Lab02 - ${{ github.actor }} is calling Composite Actions 🚀
permissions: read-all
on:
  workflow_dispatch:
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-dotnet-app
        with:
          folder-path: apps/uptodate-app
  use-reusable-workflow-greeter:
    uses: ./.github/workflows/greeter.yml
    with:
      person-name: Gaby
  publish-artifact:
    needs: build-app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v4
        with:
          name: produced-artifact
          path: ${{ needs.build-app.outputs.output-directory-path }}
